FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN cd cms && mvn clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/cms/target/*.jar app.jar
EXPOSE 8080
ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql.railway.internal:3306/railway
ENV SPRING_DATASOURCE_USERNAME=root
ENV SPRING_DATASOURCE_PASSWORD=TMkTmWIrpNvJioMaTRyfGWjIokQISwNy
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
ENV SERVER_PORT=8080
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_MAIL_HOST=smtp-relay.brevo.com
ENV SPRING_MAIL_PORT=587
ENV SPRING_MAIL_USERNAME=a4826d001@smtp-brevo.com
ENV SPRING_MAIL_PASSWORD="xsmtpsib-744ee59c5706b80e44bb60a772bbdef7733a0636a98b14a7afa72637ef4e78c9-J87ha85dg13Nvy2T"
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=10000
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=10000
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=10000
ENTRYPOINT ["java", "-jar", "app.jar"]
