spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a4826d001@smtp-brevo.com
spring.mail.password="xsmtpsib-744ee59c5706b80e44bb60a772bbdef7733a0636a98b14a7afa72637ef4e78c9-J87ha85dg13Nvy2T"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
